language: cpp

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo wget -O boost_1_65_1.tar.gz http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.gz/download
  - sudo tar xzvf boost_1_65_1.tar.gz > /dev/null
  - cd boost_1_65_1/
  - sudo ./bootstrap.sh --prefix=/usr/local --with-libraries=test
  - sudo ./b2 -d0 install 
  - cd ..

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt-5.12.3-bionic"
          packages:
            - gcc-7
            - g++-7
            - build-essential
            - qt512-meta-full
            - libgl1-mesa-dev
      env: 
        - CC_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - CONFIG=RelWithDebInfo
    - os: osx
      osx_image: xcode10
      compiler: clang

script:
  - cmake . -DBoost_USE_STATIC_LIBS=ON -DBUILD_TESTS=ON
  - cmake --build . -- -j3
  - ctest -j3

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_suucess: never
    on_failure: always